      SUBROUTINE AHNFNC
C     CALCULATES THE REFRACTIVE INDEX AND ITS GRADIENT USING THE
C     APPLETON-HARTREE FORMULA - NO FIELD, NO COLLISIONS
      COMMON /CONST/ PI,PIT2,PID2,DEGS,RADIAN,K,C,LOGTEN
      COMMON /RIN/ MODRIN(3),COLL,FIELD,SPACE,KAY2,KAY2I,
     1 H,HI,PHPT,PHPTI,PHPR,PHPRI,PHPTH,PHPTHI,PHPPH,PHPPHI,
     2 PHPOM,PHPOMI,PHPKR,PHPKRI,PHPKTH,PHPKTI,PHPKPH,PHPKPI,
     3 KPHPK,KPHPKI,POLAR,POLARI,LPOLAR,LPOLRI,SGN
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX
      COMMON /YY/ MODY,Y,PYPR,PYPTH,PYPPH,YR,PYRPR,PYRPT,PYRPP,
     1 YTH,PYTPR,PYTPT,PYTPP,YPH,PYPPR,PYPPT,PYPPP
      COMMON /ZZ/ MODZ,Z,PZPR,PZPTH,PZPPH
      COMMON /RK/ N,STEP,MODE,E1MAX,E1MIN,E2MAX,E2MIN,FACT,RSTART
      COMMON R(6) /WW/ ID(10),WQ,W(400)
      
      EQUIVALENCE (RAY,W(1)), (F,W(6))
      LOGICAL SPACE
      CHARACTER*6 MODX, MODY, MODZ
      CHARACTER*8 MODRIN
      REAL KR,KTH,KPH,K2,KPHPK,KPHPKI,KAY2,KAY2I,N2,NNP,LPOLAR,LPOLRI
      REAL I
      
      DATA MODRIN /'APPLETON', '-HARTREE', ' FORMULA'/
      DATA COLL /0.0/, FIELD /0.0/

      ENTRY RINDEX
      
      KAY2I = 0.0
      HI = 0.0
      PHPTI = 0.0
      PHPRI = 0.0
      PHPTHI = 0.0
      PHPPHI = 0.0
      PHPOMI = 0.0
      PHPKRI = 0.0
      PHPKTI = 0.0
      PHPKPI = 0.0
      KPHPKI = 0.0
      POLARI = 0.0
      LPOLRI = 0.0

      KR = R(4)
      KTH = R(5)
      KPH = R(6)

      OM = PIT2 * F * 1.0E6
      C2 = C * C
      K2 = KR*KR + KTH*KTH + KPH*KPH
      OM2 = OM * OM

      CALL ELECTX
      
      PNPX = -0.5
      PNPR = PNPX * PXPR
      PNPTH = PNPX * PXPTH
      PNPPH = PNPX * PXPPH
      PNPT = PNPX * PXPT

      N2 = 1.0 - X
      SPACE = N2 .EQ. 1.0
      NNP = N2 - 2.0*X*PNPX
      
      KAY2 = OM2 / C2 * N2
      IF (RSTART .EQ. 0.0) GO TO 1
      IF (K2 .NE. 0.0) THEN
         SCALE = SQRT(KAY2 / K2)
         KR = SCALE * KR
         KTH = SCALE * KTH
         KPH = SCALE * KPH
      END IF
 1    CONTINUE

C     CALCULATES A HAMILTONIAN H
      H = 0.5 * (C2*K2/OM2 - N2)

C     AND ITS PARTIAL DERIVATIVES WITH RESPECT TO
C     TIME, R, THETA, PHI, OMEGA, KR, KTHETA, AND KPHI.
      PHPT = -PNPT
      PHPR = -PNPR
      PHPTH = -PNPTH
      PHPPH = -PNPPH
      PHPOM = -NNP / OM
      PHPKR = C2/OM2*KR
      PHPKTH = C2/OM2*KTH
      PHPKPH = C2/OM2*KPH

      KPHPK = N2

      R(4) = KR
      R(5) = KTH
      R(6) = KPH

      POLAR = 0.0
      LPOLAR = 0.0

      RETURN
      END
