      SUBROUTINE AHNFWC
C     CALCULATES THE REFRACTIVE INDEX AND ITS GRADIENT USING THE
C     APPLETON-HARTREE FORMULA - NO FIELD, WITH COLLISIONS
      COMMON /CONST/ PI,PIT2,PID2,DEGS,RADIAN,K,C,LOGTEN
      COMMON /RIN/ MODRIN(3),COLL,FIELD,SPACE,KAY2,H,PHPT,PHPR,PHPTH,
     1 PHPPH,PHPOM,PHPKR,PHPKTH,PHPKPH,KPHPK,POLAR,LPOLAR,
     2 SGN
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX
      COMMON /YY/ MODY,Y,PYPR,PYPTH,PYPPH,YR,PYRPR,PYRPT,PYRPP,
     1 YTH,PYTPR,PYTPT,PYTPP,YPH,PYPPR,PYPPT,PYPPP
      COMMON /ZZ/ MODZ,Z,PZPR,PZPTH,PZPPH
      COMMON R,TH,PH,KR,KTH,KPH
      COMMON /WW/ ID(10),WQ,W(400)
      COMMON /RK/ N,STEP,MODE,E1MAX,E1MIN,E2MAX,E2MIN,FACT,RSTART
      EQUIVALENCE (RAY,W(1)), (F,W(6))
      
      LOGICAL SPACE
      CHARACTER*8 MODRIN
      CHARACTER*6 MODX, MODY, MODZ
      REAL KR,KTH,KPH,K2
      COMPLEX N2,PNPR,PNPTH,PNPPH,PNPVR,PNPVTH,PNPVPH,NNP,PNPT,
     1 POLAR,LPOLAR,I,U,PNPX,PNPZ,
     2 KAY2,H,PHPT,PHPR,PHPTH,PHPPH,PHPOM,PHPKR,PHPKTH,PHPKPH,
     3 KPHPK
      
      DATA MODRIN /'APPLETON', '-HARTREE', ' FORMULA'/
      DATA COLL /1.0/, FIELD /0.0/
      DATA I /(0.0, 1.0)/, ABSLIM /1.0E-5/

      ENTRY RINDEX
      OM = PIT2 * F * 1.0E6
      C2 = C * C
      K2 = KR*KR + KTH*KTH + KPH*KPH
      OM2 = OM * OM
      VR = C/OM * KR
      VTH = C/OM * KTH
      VPH = C/OM * KPH

      CALL ELECTX
      CALL COLFRZ

      U = CMPLX(1.0, -Z)
      
      N2 = 1.0 - X/U
      
      PNPX = -1.0 / (2.0*U)
      PNPZ = -I * X / (2.0 * U * U)

      NNP = N2 - (2.0*X*PNPX + Z*PNPZ)

      PNPR = PNPX*PXPR + PNPZ*PZPR
      PNPTH = PNPX*PXPTH + PNPZ*PZPTH
      PNPPH = PNPX*PXPPH + PNPZ*PZPPH

      PNPVR = 0.0
      PNPVTH= 0.0
      PNPVPH= 0.0

      PNPT = PNPX * PXPT

      SPACE = REAL(N2) .EQ. 1.0 .AND. ABS(AIMAG(N2)) .LT. ABSLIM
      
      POLAR = CMPLX(0.0, 1.0)
      LPOLAR = CMPLX(0.0, 0.0)

      KAY2 = OM2 / C2 * N2
      IF (RSTART .EQ. 0.0) GO TO 1
      SCALE = SQRT(REAL(KAY2) / K2)
      KR = SCALE * KR
      KTH = SCALE * KTH
      KPH = SCALE * KPH
 1    CONTINUE

C     CALCULATES A HAMILTONIAN H
      H = 0.5 * (C2*K2/OM2 - N2)

C     AND ITS PARTIAL DERIVATIVES WITH RESPECT TO
C     TIME, R, THETA, PHI, OMEGA, KR, KTHETA, AND KPHI.
      PHPT = -PNPT
      PHPR = -PNPR
      PHPTH = -PNPTH
      PHPPH = -PNPPH
      PHPOM = -NNP / OM
      PHPKR = C2/OM2*KR - C/OM*PNPVR
      PHPKTH = C2/OM2*KTH - C/OM*PNPVTH
      PHPKPH = C2/OM2*KPH - C/OM*PNPVPH

      KPHPK = N2
      RETURN
      END
