      SUBROUTINE BACKUP(HS)
      COMMON /RK/ N,STEP,MODE,E1MAX,E1MIN,E2MAX,E2MIN,FACT,RSTART
      COMMON /TRAC/ GROUND,PERIGE,THERE,MINDIS,NEWRAY,SMT
      COMMON R(20),T,STP,DRDT(20)
      COMMON /WW/ ID(10),WQ,W(400)
      
      EQUIVALENCE (EARTHR,W(2)), (INTYP,W(41)), (STEP1,W(44))
      
      REAL INTYP, HS, EARTHR, STEP1
      LOGICAL GROUND,PERIGE,THERE,MINDIS,NEWRAY,HOME

C     DIAGNOSTIC PRINTOUT
      CALL PRINTR('BACK UPO', 0.0)

C     GOING AWAY FROM THE HEIGHT HS
      HOME = DRDT(1) * (R(1) - EARTHR - HS) .GE. 0.0
      IF (HS .GT. 0.0 .AND. .NOT. HOME .OR. HS .EQ. 0.0 .AND. 
     1    DRDT(1) .GT. 0.0) GO TO 30

C     FIND NEAREST INTERSECTION OF RAY WITH THE HEIGHT HS
      DO I=1,10
        STEP = -(R(1) - EARTHR - HS) / DRDT(1)
        STEP = SIGN(AMIN1(ABS(STP),ABS(STEP)), STEP)
        IF (ABS(R(1) - EARTHR - HS) .LT. 5E-4 .AND. 
     1      ABS(STEP) .LT. 1.0) GO TO 60
        CALL PRINTR('BACK UP1', 0.0)
        MODE = 1
        RSTART = 1.0
        CALL RKAM
      END DO
      RSTART = 1.0

C     FIND NEAREST CLOSEST APPROACH OF RAY TO THE HEIGHT HS
      ENTRY GRAZE(HS)
      THERE = .FALSE.
      CALL PRINTR('GRAZE 0 ', 0.0)
      
      IF (SMT .GT. ABS(R(1) - EARTHR - HS)) GO TO 30
      DO I=1,10
        STEP = -R(4) / DRDT(4)
        STEP = SIGN(AMIN1(ABS(STP),ABS(STEP)), STEP)
        IF (ABS(R(4)) .LE. 1.0E-6 .AND. ABS(STEP) .LT. 1.0) GO TO 60
        CALL PRINTR('GRAZE 1 ', 0.0)
        MODE = 1
        RSTART = 1.0
        CALL RKAM
        RSTART = 1.0
        IF (DRDT(4)*(R(1) - EARTHR - HS) .LT. 0.0) GO TO 30
        IF (R(5) .EQ. 0.0 .AND. R(6) .EQ. 0.0) GO TO 60
      END DO

C     IF A CLOSEST APPROACH COULD NOT BE FOUND IN 10 STEPS, IT 
C     PROBABLY MEANS THAT THE RAY INTERSECTS THE HEIGHT HS
 30   CONTINUE
      CALL PRINTR('BACK UP2', 0.0)
      MODE = 1
      
C     ESTIMATE DISTANCE TO NEAREST INTERSECTION OF RAY WITH HEIGHT
C     HS BEHIND THE PRESENT RAY POINT
      STEP = (-R(4) - SQRT(R(4)**2 - 2.0*(R(1)-EARTHR-HS)*DRDT(4)))
     1       / DRDT(4)
      RSTART = 1.0
      CALL RKAM
      RSTART = 1.0

C     FIND NEAREST INTERSECTION OF RAY WITH HEIGHT HS
      DO I=1,10
        STEP = -(R(1) - EARTHR - HS)/DRDT(1)
        STEP = SIGN(AMIN1(ABS(STP),ABS(STEP)), STEP)
        IF (ABS(R(1) - EARTHR - HS) .LT. 5E-4 .AND. 
     1      ABS(STEP) .LT. 1.0) GO TO 60
        CALL PRINTR('BACK UP3', 0.0)
        MODE = 1
        RSTART = 1.0
        CALL RKAM
      END DO
      RSTART = 1.0

 50   THERE = .TRUE.
C     RESET STANDARD MODE AND INTEGRATION TYPE
 60   MODE = INTYP
      STEP = STEP1
      RETURN
      END
