      SUBROUTINE CHAPX
      COMMON /CONST/ PI,PIT2,PID2,DEGS,RAD,K,DUM
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX
      COMMON R(6) /WW/ ID(10),WQ,W(400)
      EQUIVALENCE (THETA,R(2))
      EQUIVALENCE (EARTHR,W(2)),(F,W(6)),(FC,W(101)),(HM,W(102)),
     1 (SH,W(103)),(ALPHA,W(104)),(A,W(105)),(B,W(106)),(C,W(107)),
     2 (E,W(108)),(PERT,W(150))
      CHARACTER*6 MODX
      DATA MODX(1)/'CHAPX'/
      ENTRY ELECTX
      THETA2=THETA-PID2
      HMAX =HM+EARTHR*E*THETA2
      H=R(1)-EARTHR
      Z=(H-HMAX)/SH
      D=0.0
      IF (B.NE.0.0) D=PIT2/B
      TEMP =1.0+A*SIN(D*THETA2)+C*THETA2
      EXZ =1.0-EXP(-Z)
      X=(FC/F)**2*TEMP*EXP(ALPHA*(EXZ-Z))
      PXPR =-ALPHA*X*EXZ/SH
      PXPTH =X*(D*A*SIN(PID2-D*THETA2)+C)/TEMP-PXPR*EARTHR*E
      PXPPH=0.0
      RETURN
      END