      SUBROUTINE EXPX
      COMMON /CONST/ PI,PIT2,PID2,DEGS,RAD,K,DUM(2)
      COMMON /XX/ MODX(2),X(6),HMAX,PXPR,PXPTH,PXPPH
      COMMON R(6) /WW/ ID(10),WQ,W(400)
      EQUIVALENCE (EARTHR,W(2)),(F,W(6)),
     1 (NO,W(101)),(HO,W(102)),(A,W(103)),(PERT,W(150))
      REAL N,NO,K
      CHARACTER*8 MODX
      ENTRY ELECTX
      H=R(1)-EARTHR
      N=NO*EXP(A*(H-HO))
      X(1)=K*N/F**2
      PXPR=A*X(1)
      PXPTH=0.0
      PXPPH=0.0
      IF (PERT.NE.0.0) CALL ELECT1
      RETURN
      END