      SUBROUTINE HAMLTN
C     CALCULATES HAMILTONS EQUATIONS FOR RAY TRACING
      COMMON /CONST/ PI,PIT2,PID2,DEGS,RADIAN,K,C,LOGTEN
      COMMON /RIN/ MODRIN(3),COLL,FIELD,SPACE,KAY2,KAY2I,
     1 H,HI,PHPT,PHPTI,PHPR,PHPRI,PHPTH,PHPTHI,PHPPH,PHPPHI,
     2 PHPOM,PHPOMI,PHPKR,PHPKRI,PHPKTH,PHPKTI,PHPKPH,PHPKPI,
     3 KPHPK,KPHPKI,POLAR,POLARI,LPOLAR,LPOLRI,SGN
      COMMON R(20),T,STP,DRDT(20) 
      COMMON /WW/ ID(10),WQ,W(400)

      REAL KR,KTH,KPH,KPHPK,KPHPKI,POLAR,LPOLRI,LOGTEN,K
      REAL KAY2,KAY2I,H,HI,PHPT,PHPTI,PHPR,PHPRI,PHPTH,PHPTHI
      REAL PHPPH,PHPPHI,PHPOM,PHPOMI,PHPKR,PHPKRI,PHPKTH,PHPKTI
      REAL PHPKPH,PHPKPI
      
      EQUIVALENCE (TH, R(2)), (PH, R(3)), (KR, R(4)), (KTH, R(5)), 
     1 (KPH, R(6))
      EQUIVALENCE (DTHDT, DRDT(2)), (DPHDT, DRDT(3)), (DKRDT, DRDT(4)),
     1 (DKTHDT, DRDT(5)), (DKPHDT, DRDT(6)), (F, W(6))
      
      REAL TH, PH, DTHDT, DPHDT, DKRDT, DKTHDT, DKPHDT, F

      LOGICAL SPACE
      CHARACTER*8 MODRIN
      
      OM = PIT2 * 1.0E6 * F
      STH = SIN(TH)
      CTH = SIN(PID2 - TH)
      
      RSTH = R(1) * STH
      RCTH = R(1) * CTH
      
      CALL RINDEX
      
      DRDT(1) = -PHPKR / (PHPOM * C)
      DTHDT = -PHPKTH / (PHPOM * R(1) * C)
      DPHDT = -PHPKPH / (PHPOM * RSTH * C)
      DKRDT = PHPR / (PHPOM * C) + KTH*DTHDT + KPH*STH*DPHDT
      DKTHDT = PHPTH / (PHPOM * C) - (TH*DRDT(1) + KPH*RCTH*DPHDT)/R(1)
      DKPHDT = PHPPH / (PHPOM * C) - KPH*STH*DRDT(1) / RSTH
      DKPHDT = DKPHDT - KPH*RCTH*DTHDT / RSTH

      NR = 6

C.........PHASE PATH
      IF (W(57) .EQ. 0.0) GO TO 10
      NR = NR + 1
      DRDT(NR) = KPHPK / PHPOM / OM

C.........ABSORPTION
 10   IF (W(58) .EQ. 0.0) GO TO 15
      NR = NR + 1
      DRDT(NR) = 10.0 / LOGTEN * KPHPKI * KAY2I /
     1           (KR*KR + KTH*KTH + KPH*KPH) / PHPOM / C

C.........DOPPLER SHIFT
 15   IF (W(59) .EQ. 0.0) GO TO 20
      NR = NR + 1
      DRDT(NR) = -PHPT / PHPOM / C / PIT2

C.........GEOMETRICAL PATH LENGTH
 20   IF (W(60) .EQ. 0.0) GO TO 25
      NR = NR + 1
      DRDT(NR) = SQRT(PHPKR**2 + PHPKTH**2 + PHPKPH**2) / PHPOM

 25   CONTINUE
C.........OTHER CALCULATIONS

      RETURN
      END
