      SUBROUTINE RAYPLT
C     REPLACES SUBROUTINES RAYPLT, PLOT, AND LABPLT IF PLOTS ARE
C     NOT WANTED OR IF A PLOTTER IS NOT AVAILABLE
      COMMON /WW/ ID(10),WQ,W(400)
      EQUIVALENCE (PLT,W(81))
      PLT = 0.0
      ENTRY ENDPLT
      RETURN
      END
