      SUBROUTINE REACH
C     CALCULATES THE STRAIGHT LINE RAY PATH BETWEEN THE EARTH
C     AND THE IONOSPHERE OR BETWEEN IONOSPHERIC LAYERS
      COMMON /RK/ N,STEP,MODE,E1MAX,E1MIN,E2MAX,E2MIN,FACT,RSTART
      COMMON /TRAC/ GROUND,PERIGE,THERE,MINDIS,NEWRAY,SMT
      COMMON /COORD/ S
      COMMON /RIN/ MODRIN(3),COLL,FIELD,SPACE,KAY2,KAY2I,H,HI,PHPT,
     1 PHPTI,PHPR,PHPRI,PHPTH,PHPTHI,PHPPH,PHPPHI,PHPOM,PHPOMI,
     2 PHPKR,PHPKRI,PHPKTH,PHPKTI,PHPKPH,PHPKPI,KPHPK,KPHPKI,
     3 POLAR,POLARI,LPOLAR,LPOLRI,SGN
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX
      COMMON R(20),T,STP,DRDT(20) 
      COMMON /WW/ ID(10),WQ,W(400)
      
      EQUIVALENCE (EARTHR,W(2)),(XHTRH,W(3)),(RCVRH,W(20))
      LOGICAL CROSS,CROSSG,CROSSR,SPACE,GROUND,PERIGE,THERE,MINDIS,
     1 NEWRAY,RSPACE
      REAL INTYP, XHTRH, RCVRH, EARTHR
      COMPLEX KAY2,KAY2I,H,HI,PHPT,PHPTI,PHPR,PHPRI,PHPTH,PHPTHI
      COMPLEX PHPPH,PHPPHI,PHPOM,PHPOMI,PHPKR,PHPKRI,PHPKTH,PHPKTI
      COMPLEX PHPKPH,PHPKPI,KPHPK,KPHPKI,POLAR,POLARI,LPOLAR,LPOLRI
      
      DATA NSTEP /500/
      
      CALL HAMLTN
      H_VAL = R(1) - EARTHR
      IF (.NOT.NEWRAY .AND. .NOT.RSPACE) CALL PRINTR('EXIT ION',0.0)
      NEWRAY = .FALSE.
      V = SQRT(R(4)**2 + R(5)**2 + R(6)**2)
      
C     NORMALIZE WAVE NORMAL DIRECTION TO ONE
      R(4) = R(4)/V
      R(5) = R(5)/V
      R(6) = R(6)/V

C     NEGATIVE OF DISTANCE ALONG RAY TO CLOSEST APPROACH TO CENTER OF EARTH
      UP = R(1)*R(4)
      RADG = EARTHR**2 - R(1)**2*(R(5)**2 + R(6)**2)
      DISTG = SQRT(AMAX1(0.0, RADG))

C     DISTANCE ALONG RAY TO FIRST INTERSECTION WITH OR CLOSEST APPROACH TO EARTH
      SG = -UP - DISTG

C     CROSSG IS TRUE IF THE RAY WILL INTERSECT OR TOUCH THE EARTH
      CROSSG = -UP .GT. 0.0 .AND. RADG .GE. 0.0
      RADR = (EARTHR+RCVRH)**2 - R(1)**2*(R(5)**2 + R(6)**2)
      DISTR = SQRT(AMAX1(0.0, RADR))

C     DISTANCE ALONG RAY TO THE FIRST INTERSECTION WITH OR CLOSEST APPROACH TO RECEIVER HEIGHT
      SR = DISTR - UP
      IF (UP .LT. 0.0 .AND. DISTR .LT. -UP .AND. 
     1    R(1) .NE. EARTHR+RCVRH) SR = -DISTR - UP

C     CROSSR IS TRUE IF THE RAY WILL INTERSECT WITH OR MAKE A CLOSEST APPROACH TO RECEIVER
      CROSSR = CROSSG .OR. CROSSR
      
C     MAXIMUM DISTANCE IN WHICH TO LOOK FOR THE IONOSPHERE
      S1 = AMIN1(SR, SG)
      IF (.NOT. CROSSG) S1 = SR
      IF (UP .GE. 0.0) GO TO 15
      CROSS = .TRUE.
C     IF RAY IS GOING DOWN, S1 IS AT MOST THE DISTANCE TO A PERIGEE
      S1 = AMIN1(S1, -UP)

C     CONVERT THE POSITION AND DIRECTION OF THE RAY TO CARTESIAN COORDINATES
 15   CALL POLCAR
      SSTEP = 100.0
      S = SSTEP
      
      DO I=1,NSTEP
        IF (ABS(S-SSTEP) .GT. S1 .AND. CROSS) GO TO 25
C       CONVERT POSITION AND DIRECTION TO SPHERICAL POLAR COORDINATES
C       AT A DISTANCE S ALONG THE RAY
        CALL CARPOL
        CALL ELECTX
C       IF RAY IN THE IONOSPHERE, STEP BACK OUT
        IF (X .EQ. 0.0) GO TO 20
        CALL RINDEX
C       EFFECTIVELY FREE SPACE
        IF (SPACE) GO TO 20
        IF (SSTEP .LT. 0.5E-4) GO TO 25
C       RAY IN THE IONOSPHERE, STEP BACK OUT AND DECREASE STEP SIZE
        S = S - SSTEP
        SSTEP = SSTEP / 10.0
 20     S = S + SSTEP
      END DO
 
      PRINT 2000, NSTEP
 2000 FORMAT (9H EXCEEDED, I5, 25H STEPS IN SUBROUTINE REACH)
      STOP
      
 25   IF (CROSS) S = AMIN1(S, S1)
C     CONVERT POSITION AND DIRECTION TO SPHERICAL POLAR COORDINATES
C     AT A DISTANCE S ALONG THE RAY
      CALL CARPOL
C     AVOID THE RAY BEING SLIGHTLY UNDERGROUND
      R(1) = AMAX1(R(1), EARTHR)

C     ONE STEP INTEGRATION COORDINATES
      IF (N .LT. 7) GO TO 31
      DO NN_IDX=7,N
        R(NN_IDX) = R(NN_IDX) + S*DRDT(NN_IDX)
      END DO
 31   T = T + S
      CALL RINDEX
      
C     PERIGEE
      PERIGE = S .EQ. (-UP)
      IF (PERIGE) R(4) = 0.0
      DRDT(1) = R(4)
      
C     ON THE GROUND
      GROUND = S .EQ. SG .AND. CROSSG
C     AT THE RECEIVER HEIGHT
      THERE = S .EQ. SR .AND. CROSSR .AND. .NOT. PERIGE
C     AT A CLOSEST APPROACH TO THE RECEIVER HEIGHT
      MINDIS = PERIGE .AND. S .EQ. SR .AND. CROSSR
      
      RSPACE = SPACE
      V = SQRT(REAL(N2)/(R(4)**2 + R(5)**2 + R(6)**2))
      
C     RENORMALIZE THE WAVE NORMAL DIRECTION
      R(4) = R(4) * V
      R(5) = R(5) * V
      R(6) = R(6) * V
      
      RSTART = 1.0
      IF (.NOT. SPACE) CALL PRINTR('ENTR ION', 0.0)
      
      RETURN
      END
