      SUBROUTINE READW
C     READS W ARRAY
C     A 1 IN THE FOLLOWING COLUMNS WILL MAKE THE DESCRIBED CONVERSIONS
C     COL 18  DEGREES TO RADIANS
C     COL 19  GREAT CIRCLE DISTANCE IN KM TO RADIANS
C     COL 20  NAUTICAL MILES TO KM
C     COL 21  FEET TO KM
      COMMON /CONST/ PI,PIT2,PID2,DEGS,RAD,DUM(3)
      COMMON /WW/ ID(10),WQ,W(400)
      EQUIVALENCE (EARTHR,W(2))
      INTEGER DEG,FEET

      READ (5, 1000) ID
 1000 FORMAT (10A8)

 4    READ (5, 1100, END=3) NW, W(MAX0(1,NW)), DEG, KM, NM, FEET
 1100 FORMAT (I3, E14.7, 4I1)

      IF (NW .EQ. 0) GO TO 10
      IF (NW .GT. 0 .AND. NW .LE. 400) GO TO 5
      PRINT 4000, NW
 4000 FORMAT (15H THE SUBSCRIPT , I3, 
     1 44H ON THE W-ARRAY INPUT IS OUT OF BOUNDS.     )
      STOP

 5    IF (DEG .NE. 0) W(NW) = W(NW) * RAD
      IF (KM .NE. 0) W(NW) = W(NW) / EARTHR
      IF (NM .NE. 0) W(NW) = W(NW) * 1.852
      IF (FEET .NE. 0) W(NW) = W(NW) * 3.048006096E-4
      GO TO 4

 3    STOP 'END OF INPUT'
 10   RETURN
      END
