      SUBROUTINE SWNF
C     CALCULATES THE REFRACTIVE INDEX AND ITS GRADIENT USING THE
C     SEN-WYLLER FORMULA -- NO FIELD
C     NEEDS SUBROUTINES FGSW AND FSW AND FUNCTIONS C AND S.
      COMMON /CONST/ PI,PIT2,PID2,DEGS,RADIAN,K,SEA,LOGTEN
      COMMON /RIN/ MODRIN(3),COLL,FIELD,SPACE,KAY2,KAY2I,
     1 H,HI,PHPT,PHPTI,PHPR,PHPRI,PHPTH,PHPTHI,PHPPH,PHPPHI,
     2 PHPOM,PHPOMI,PHPKR,PHPKRI,PHPKTH,PHPKTI,PHPKPH,PHPKPI,
     3 KPHPK,KPHPKI,POLAR,POLARI,LPOLAR,LPOLRI,SGN
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX
      COMMON /YY/ MODY,Y(10)
      COMMON /ZZ/ MODZ,Z,PZPR,PZPTH,PZPPH
      COMMON /RK/ N,STEP,MODE,E1MAX,E1MIN,E2MAX,E2MIN,FACT,RSTART
      COMMON R(6) /WW/ ID(10),WQ,W(400)
      
      EQUIVALENCE (RAY,W(1)), (F,W(6))
      LOGICAL SPACE
      CHARACTER*6 MODX, MODY, MODZ
      CHARACTER*8 MODRIN
      REAL KR,KTH,KPH,K2,OM,C2,OM2,SCALE
      
      COMPLEX KAY2,KAY2I,H,HI,PHPT,PHPTI,PHPR,PHPRI,PHPTH,PHPTHI
      COMPLEX PHPPH,PHPPHI,PHPOM,PHPOMI,PHPKR,PHPKRI,PHPKTH,PHPKTI
      COMPLEX PHPKPH,PHPKPI,KPHPK,KPHPKI,POLAR,POLARI,LPOLAR,LPOLRI
      COMPLEX PNPX,PNPZ,F1,DF1,G1,DG1
      COMPLEX N2,PNPR,PNPTH,PNPPH,PNPVR,PNPVTH,PNPVPH,NNP,PNPT

      DATA MODRIN /'SEN-WYLL','ER FORMU','LA      '/
      DATA COLL /1.0/, FIELD /0.0/
      DATA POLAR /(0.0, 1.0)/, LPOLAR /(0.0, 0.0)/
      DATA ABSLIM /1.0E-5/, PNPVR /(0.0, 0.0)/, PNPVTH /(0.0, 0.0)/
      DATA PNPVPH /(0.0, 0.0)/
      
      ENTRY RINDEX
      
      KAY2I = CMPLX(0.0,0.0)
      HI = CMPLX(0.0,0.0)
      PHPTI = CMPLX(0.0,0.0)
      PHPRI = CMPLX(0.0,0.0)
      PHPTHI = CMPLX(0.0,0.0)
      PHPPHI = CMPLX(0.0,0.0)
      PHPOMI = CMPLX(0.0,0.0)
      PHPKRI = CMPLX(0.0,0.0)
      PHPKTI = CMPLX(0.0,0.0)
      PHPKPI = CMPLX(0.0,0.0)
      KPHPKI = CMPLX(0.0,0.0)
      POLARI = CMPLX(0.0,0.0)
      LPOLRI = CMPLX(0.0,0.0)

      KR = R(4)
      KTH= R(5)
      KPH= R(6)
      
      OM = PIT2 * 1.0E6 * F
      C2 = SEA * SEA
      K2 = KR*KR + KTH*KTH + KPH*KPH
      OM2 = OM * OM
      
      CALL ELECTX
      CALL COLFRZ
      
      CALL FGSW(1.0/Z, F1, DF1, G1, DG1)
      N2 = 1.0 - X*G1
      
C     The analytical gradient is dH/dX = 0.5 * d(-N2)/dX = 0.5 * G1
      PNPX = 0.5 * G1
      PNPZ = 0.5 * X * DG1 / (Z**2)
      
      PNPR = PNPX*PXPR + PNPZ*PZPR
      PNPTH= PNPX*PXPTH + PNPZ*PZPTH
      PNPPH= PNPX*PXPPH + PNPZ*PZPPH
      
      NNP = N2 - (2.0*X*PNPX + Z*PNPZ)
      PNPT = PNPX * PXPT
      
      SPACE = REAL(N2) .EQ. 1.0 .AND. ABS(AIMAG(N2)) .LT. ABSLIM
      KAY2 = OM2 / C2 * N2
      
      IF (RSTART .EQ. 0.0) GO TO 1
      IF (REAL(K2) .NE. 0.0) THEN
         SCALE = SQRT(REAL(KAY2)/K2)
         KR = SCALE * KR
         KTH= SCALE * KTH
         KPH= SCALE * KPH
      END IF
 1    CONTINUE

      H = 0.5*(C2*K2/OM2 - N2)
      
      PHPT = -PNPT
      PHPR = -PNPR
      PHPTH = -PNPTH
      PHPPH = -PNPPH
      PHPOM = -NNP / OM
      
      PHPKR = C2/OM2 * KR
      PHPKTH= C2/OM2 * KTH
      PHPKPH= C2/OM2 * KPH
      
      KPHPK = N2
      
      R(4) = KR
      R(5) = KTH
      R(6) = KPH
      
      RETURN
      END
