      SUBROUTINE VCHAPX
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX
      COMMON R(6) /WW/ ID(10),WQ,W(400)
      EQUIVALENCE (EARTHR,W(2)),(F,W(6)),(FC,W(101)),(HM,W(102)),
     1 (CHI,W(103)),(PERT,W(150))
      CHARACTER*6 MODX
      DATA MODX(1) /'VCHAPX'/
      ENTRY ELECTX
      HMAX=HM
      X=0.0
      PXPR=0.0
      PXPTH=0.0
      PXPPH=0.0
      H=R(1)-EARTHR
      IF (H.LE.0.0) GO TO 50
      TAU=(HM/H)**CHI
      X=(FC/F)**2*SQRT(TAU)*EXP(0.5*(1.0-TAU))
      PXPR=.5*X*(TAU-1.0)*CHI/H
50    IF (PERT.NE.0.0) CALL ELECT1
      RETURN
      END