SUBROUTINE AHWFNC
CALCULATES THE REFRACTIVE INOEX ANO ITS GRAOIENT USING THE
APPLETON-HARTREE FOR~ULA wITH FIELO, NO COLLISIONS
COHNON ICONSTI PI,PITZ,PI02;OEGS,RAOIAN,K,C,LOGTEN
~ONHON IRINI ~OOR!N(3I,COLL,FIELO,SPACE,KAY2,KAYZI,

WFNC001
WFNCOOZ
WFNC003
WFNCOO~

WFNCOOS

H,HI,PHPT,P~PTI,PHPR,PHPRI,PHPTH,PHPTHI,PHPPH,PHPPHIWF NCaD6
,PH POM, PHPOMI, PH~K.R, PHPKR I ,PHPI<TH, PHPKT I , PHPICPH, PHPKPIWFHCaa 7

1
2

3
COHMON
COHMON

,K PHPK ,KPHPKI, PO LA R,POLARI,LPOLAR, LPOLRI, SGN
WFNC 00 6
IXXI ~OOX(2),X,PXPRtPXPTH,PXPPH,PXPT,HHAX
WFNC009
IYYI HOOY,Y,PYPR,PYPTH,PYPPH,YR,PYRPR,PYRPT.PVRPP,YTH,PYTPRHFNC010

1

,PYTPT,PYTPP,VPH,PYPPR,PYPPT,PYPPP

CJNHON Illl HOOl,l(~1
COHHON IRKI N,STEP,HOOE,E1HAX,E1NIN,EZHAX,EZHIN,FACT,RSTART
~OHHON ~,TH,~H,KR,KTH,KPti
IWH/IO(lD},WO,W(4DO'
EQUIVALENCE (UY,H(1II,(F,W(611
LOGICAL SPACE
REAL

KR.KTH,KPH,K2,KPHPK,KPHPKI,ICAY2,KAY2I,N2,N~P,LPOlAR,LP OLRI

DATA (HOORIN=6HAPFLETON,8H-HARTREE,8H FORMULAI,(COLL=O.I,
1
(FI EL 0= 1. I , ( KAYZ I =0. I , ( HI = O. I , ( PH PTI = O. I , ( PHPR 1= 0 .) ,
2
(PHPTHI=O.I,(PHPPHI=O') ,IPHPOHI=O.I, (PHPKRI=O.I,(PHPKTI=O .1,
3
(PHPKPI=D.I,(KPHPKI=O.I,(POLAR=O.I,(LPOLAR=O.I,
(X=O . ), (DXPR=O.), (PXPTH=O.),(P)(PPH=O.),(PXPT=O.).
(Y = 0 • , t (P Y PR= 0 • ) , (PY P T H =0 • ) , ( PY PP H=D • ) , (Y R= 0 • ) , ( PYR?R=O • ) ,
(PYRPT=O.) ,(P'YRPP=O.) t (YTH=O.), (PYTPR=O.) ,(PYTPT=O.) t
t P Y T PP= o. } • ( Y PH= 0 • ) t (P Y PP R = 0 • ) , (P YP;:) T= 0 • ) , ( py ppp = 0 .) ,

It
:;;

51
7

6

HFH C07S
HFHC076
HFHC077
HFWC078
WFHC079
WFHC080
WFHC08Z
HFHC083

KPHPK=NZ
RETURN
ENO

C
C

HFHC066
HFHC067
HFHC066
HFHC069
HFHC070
HFHC 071
WFHC07Z
HFHC073

(MOOl=lM I, (U=1.1
ENTRY RINJE X

WFHe011

WFNC012
WFNC013
WFNe01,.

WFNC01S
WFNC016
WFNCD17

WFNC016
WFN COL 9
WFNCOZO
WFNCOZ1
WFNCD22
WFN C02 3
WFNC024
HF NCO 2 5

"FNCOZ6
WFNCOZ7

OH=prT2.1.Eo·~

WFNC026

CZ=C"C

WFNCOZ9

K2=KR.KR+KTH.KTH+KPH.KPH

WFNC030

J .~2=OH'OH

VTH=C/OM"KT1

WFNC031
WFNCOJZ
WFNCOJ3

~PH=C/O~.(P~

WFNC034

V~

=C/OH"~R

94

CALL ELECTX
:ALL MAGY
~2=~R··Z+~TH··2+~PH··Z
~OOTY=~R·YR+~TH·YTH+~PH·YPH

YLV=VOOTYIV2
YL2=vDOTY··ZI1/2
YT2=Y··Z-YL2

YTI+=YT2".,T2
UX=U-X
UX2=UX·UX
RAO=RAY·SlRTIYT4+4.·YL2·UX21
O=Z."UK-YTZ+RAO
02 =O' 0
N2=1.-2.·x·UX/O
PNPPS=2.·X·UX"(-1.+(YT2-Z."UXZ)/RAOl/02
??SPR= YL2/Y.'YPR -(VR·PYRPR+"TH.PYTPR+VPH.PYPPR).YL~

PPSPTH=YLZ/Y·PYPTH-{VR·PYRPT+VTH"PYTPT+V'PH·PYPPT)·Ylv
PPSPPH=YLZ/Y·PYPPH-(VR"PYRPPtVTHiJPVTPP+V'PH"PYPPP)·YLV
PNPX=-(2.·UX2-YT2·(U-2.·X)+(YT~·(U-2.·X)+4.·YL2·UX·UXZ J/RAOJ/OZ

PNPY=2."X·UX·(-YT2+(YT4+2.·YLZ·UXZ'/RAO)/(OZ"Y)
NNP=N2-(2.·X·~NPX+Y·PNPY)

PNPR =PNPX"PXPR tPNPY·PYPR tPNPPS.PPSPR
PNPTH=PNPK·PXPTH+PNPY·PY~TH+PNPPS·PPSPTH

PNPPH=PNPX·PXPPHtPNPY·PYPPH+PNPPS·PPSPPH
PNPVR =PNPPS'IVR 'YL2-VOOTY'YR I/V2
PNPVTH=PNPPS'IVTH'YL2-VOOTY'YTH)IV2
PNPVPH=PNPPS'IVPH'YL2-VOOTY'YPH)/V2
PNPT=PNPX< PX PT

SP'ACE=NZ.EQ.1.
POLARI=SQRTIVZ)·IYT2-RAOIIIZ.·VOOTY·UXI

GAH=(-YT2+RAO)/ (Z •• UX)
LPOLRI=X'SQRTIYT21/IUX'IU+GAMI)
~AY2=OMZI:2'N2

IFIRSTART.EQ.O.) GO TO 1
SCALE=SQRTIKAr2I(2)
KR :SCALE'KR
KTH=SCALE'KTH
K~H=SCALE'K?~

1

CONTINUE

C········· CALCULATES A HA"ILTO~IAN H
H=.5·IC2·K210~2-N2)

C······
••• AND ITS PARTIAL DERIVATIVES WITH RESPECT TO
C········· TIME, R, THETA, PHI, OMEGA, KR, KTHETA, AND KPHI.
PHPT =-PNPT
P~PR =-PNPR
PHPTH=- PNPT~
PHPPH=-PNPPH
?HPOM=-NNP/O~

PHPKR =C2/0~Z'KR -C/OM'P~PVR
PHPKTH=CZ/OMZ'KTH-C/OH'PNPVTH
PHPKPH=C210M2'KPH-CIOM'PNPVPH
KPHPK=N2
RETURN
ENO

95

WFNC035
WFNC036
WFNC037
WFNC038
WFNC039
WFNCO.O
WFNC041
WFNC042
WFNC043
WFNCO.4
WFNC045
WFNCQ46

WFNC047
WFNC048
WFNCO.9
WFNCOSO
WFNC051
WFNCOS2
WFNCOS3
WFNCOS4
WFNCOSS
WFNC056
WFNC057
WFNCOS8
WFNCOS9
WFNC060
WFNC061
WFNC062
WFNC063
WFNC064
WFNC06S
WFNC066
WFNCOf>7
WFNC068
WFNC069
WFNC070
WFNC071
WFNC072
WFNC073
WFNC074
WFHC075
WFHC076
WFHC077
WFHC078
WFHC079
WFHC080
WFNC081
WFNC082
WFNC083
WFNC084
WFNC08S
WFNC086
WFNC087
WFNC088-
