      PROGRAM TEST_SWWF
      COMMON /CONST/ PI,PIT2,PID2,DEGS,RADIAN,K,SEA,LOGTEN
      COMMON /RIN/ MODRIN(3),COLL,FIELD,SPACE,KAY2,KAY2I,
     1 H,HI,PHPT,PHPTI,PHPR,PHPRI,PHPTH,PHPTHI,PHPPH,PHPPHI,
     2 PHPOM,PHPOMI,PHPKR,PHPKRI,PHPKTH,PHPKTI,PHPKPH,PHPKPI,
     3 KPHPK,KPHPKI,POLAR,POLARI,LPOLAR,LPOLRI,SGN
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX
      COMMON /ZZ/ MODZ,Z,PZPR,PZPTH,PZPPH
      COMMON R(6) /WW/ ID(10),WQ,W(400)
      COMMON /RK/ N,STEP,MODE,E1MAX,E1MIN,E2MAX,E2MIN,FACT,RSTART
      
      EQUIVALENCE (RAY,W(1)), (F,W(6)), (EARTHR, W(2)), (READFN,W(100))
      LOGICAL SPACE
      CHARACTER*6 MODX, MODZ
      CHARACTER*8 MODRIN
      COMPLEX KAY2, KAY2I, H, HI, PHPT, PHPTI, PHPR, PHPRI, PHPTH
      COMPLEX PHPTHI, PHPPH, PHPPHI, PHPOM, PHPOMI, PHPKR, PHPKRI
      COMPLEX PHPKTH, PHPKTI, PHPKPH, PHPKPI, KPHPK, KPHPKI, POLAR
      COMPLEX POLARI, LPOLAR, LPOLRI

      C = 299792.458
      SEA = C
      PI = 3.14159265
      PIT2 = 2.0 * PI
      F = 10.0
      RAY = 1.0 ! ordinary ray
      RSTART = 0.0
      SGN = 1.0

      R(4)=0.0
      R(5)=0.0
      R(6)=0.0
      R(1) = EARTHR + 100.0

      X = 0.0
      Y = 0.5
      YR = Y
      YTH = 0.0
      YPH = 0.0
      Z = 0.5
      READFN = 0.0

      CALL RINDEX

      PRINT *, 'Test for SWWF'
      PRINT *, 'N2 / KPHPK = ', KPHPK
      PRINT *, 'H          = ', H

      IF (ABS(REAL(KPHPK) - 1.0) .LT. 1.0E-5 .AND.
     +    ABS(REAL(H) - (-0.5)) .LT. 1.0E-5) THEN
        PRINT *, 'Test PASSED'
      ELSE
        PRINT *, 'Test FAILED'
      END IF

      END PROGRAM TEST_SWWF
