C     Engine-level stubs providing RINDEX for tests that need it
C     (HAMLTN, RKAM, BACKUP, REACH, TRACE tests)
      SUBROUTINE RINDEX
      COMMON /RIN/ MODRIN(3),COLL,FIELD,SPACE,KAY2,KAY2I,
     1 H,HI,PHPT,PHPTI,PHPR,PHPRI,PHPTH,PHPTHI,PHPPH,PHPPHI,
     2 PHPOM,PHPOMI,PHPKR,PHPKRI,PHPKTH,PHPKTI,PHPKPH,PHPKPI,
     3 KPHPK,KPHPKI,POLAR,POLARI,LPOLAR,LPOLRI,SGN
      REAL KAY2,KAY2I,H,HI,PHPT,PHPTI,PHPR,PHPRI,PHPTH,PHPTHI
      REAL PHPPH,PHPPHI,PHPOM,PHPOMI,PHPKR,PHPKRI,PHPKTH,PHPKTI
      REAL PHPKPH,PHPKPI,KPHPK,KPHPKI,POLAR,POLARI,LPOLAR,LPOLRI
      LOGICAL SPACE
      CHARACTER*8 MODRIN
      
      PHPKR = -1.0
      PHPKTH= -0.5
      PHPKPH=  0.0
      PHPOM = -10.0
      PHPR  = 1.0
      PHPTH = 0.5
      PHPPH = 0.0
      PHPT  = 0.0
      KPHPK = 1.0
      KPHPKI= 0.0
      KAY2I = 0.0
      RETURN
      END
