      SUBROUTINE ELECT1
      COMMON /XX/ MODX,X(6)
      COMMON /WW/ ID(10),WQ,W(400)

      CHARACTER*6 MODX(2)

      EQUIVALENCE (PERT,W(151))

      PERT=0.
      MODX(2) = ' NONE'

      RETURN
      END