      SUBROUTINE EXPX
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX
      COMMON R(6) /WW/ ID(10),WQ,W(400)
      EQUIVALENCE (H0,W(151)),(HSC,W(152)),(XMAX,W(153))
      CHARACTER*6 MODX
      DATA MODX(1)/'EXPX'/
      ENTRY ELECT1
      HMAX=H0+5.0*HSC
      H=R(1)-HMAX
      IF (HSC.LE.0.0.OR.XMAX.EQ.0.0) RETURN
      E=EXP(H/HSC)
      X=XMAX*E
      PXPR=X/HSC
      PXPTH=0.0
      PXPPH=0.0
      RETURN
      END