      SUBROUTINE EXPX
      COMMON /CONST/ PI,PIT2,PID2,DEGS,RAD,K,DUM(2)
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX
      COMMON R(6) /WW/ ID(10),WQ,W(400)
      EQUIVALENCE (EARTHR,W(2)),(F,W(6)),
     1 (NO,W(101)),(HO,W(102)),(A,W(103)),(PERT,W(150))
      REAL N,NO,K
      CHARACTER*6 MODX
      DATA MODX(1) /'EXPX'/,HMAX /350.0/
      ENTRY ELECTX
      H=R(1)-EARTHR
      N=NO*EXP(A*(H-HO))
      X=K*N/F**2
      PXPR=A*X
      PXPTH=0.0
      PXPPH=0.0
      IF (PERT.NE.0.0) CALL ELECT1
      RETURN
      END