      SUBROUTINE SHOCK
      COMMON /CONST/ PI,PIT2,PID2,DUM(5)
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX
      COMMON R(6) /WW/ ID(10),WQ,W(400)
      EQUIVALENCE (EARTHR,W(2)),(P,W(151)),(WW,W(152)),(ALAT,W(153)),
     1 (ALON,W(154)),(S,W(155)),(HO,W(156))
      REAL LAT,LON
      CHARACTER*6 MODX
      DATA MODX(2) /'SHOCK'/
      ENTRY ELECT1
      IF (X.NE.0.0) GOTO 20
      IF (PXPR.NE.0.0) GOTO 20
      IF (PXPTH.NE.0.0) GOTO 20
      IF (PXPPH.NE.0.0) GOTO 20
      RETURN
 20   CONTINUE
      IF (P.EQ.0.0.OR.WW.EQ.0.0) RETURN
      H=R(1)-EARTHR
      RHOC=S*(H-HO)-WW
      LON=R(3)-ALON
      LAT=PID2-R(2)-ALAT
      COSLON=COS(LON)
      COSLAT=COS(LAT)
      U=COSLON*COSLAT
      RHO=R(1)*ACOS(U)
      DIF=RHOC-RHO
      CON=-9.0/WW**2
      CONS=P*EXP(CON*DIF**2)
      CONST=1.0+CONS
      CON=2.0*CON*CONS*DIF
      PXPR=PXPR*CONST+X*CON*(S-RHO/R(1))
      IF (ABS(1.0 - U*U) .GE. 1.0E-9) GOTO 30
      PXPTH=PXPTH*CONST
      PXPPH=PXPPH*CONST
      GOTO 40
 30   CONTINUE
      CONS=R(1)*1.0/SQRT(1.0-U**2)
      PXPTH=PXPTH*CONST+X*CON*CONS*COSLON*SIN(LAT)
      PXPPH=PXPPH*CONST-X*CON*CONS*COSLAT*SIN(LON)
 40   CONTINUE
      X=X*CONST
      RETURN
      END