      SUBROUTINE TORUS
      COMMON /CONST/ PI,PIT2,PID2,DUM(5)
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX
      COMMON R(6) /WW/ ID(10),WQ,W(400)
      EQUIVALENCE (EARTHR,W(2)),(CO,W(151)),(A,W(152)),(B,W(153)),
     1 (BETA,W(154)),(HO,W(155))
      REAL LAMBDA
      CHARACTER*6 MODX
      DATA PDPP /0.0/,MODX(2) /'TORUS'/
      ENTRY ELECT1
      IF (X.EQ.0.0.AND.PXPR.EQ.0.0.AND.PXPTH.EQ.0.0.AND.PXPPH.EQ.0.0) RETURN
      IF (CO.EQ.0.0) RETURN
      RO =EARTHR+HO
      Z=R(1)-RO
      LAMBDA=RO*(R(2)-PID2)
      SINBET=SIN(BETA)
      COSBET=COS(BETA)
      P=LAMBDA*COSBET+Z*SINBET
      Y=Z*COSBET-LAMBDA*SINBET
      DELTA=CO*EXP(-(P/A)**2-(Y/B)**2)
      DEL1=DELTA+1.0
      PDPR=-2.0*DELTA*(P*SINBET/A**2+Y*COSBET/B**2)
      PDPT=-2.0*DELTA*(P*RO*COSBET/A**2-Y*RO*SINBET/B**2)
      PXPR=PXPR*DEL1+X*PDPR
      PXPTH=PXPTH*DEL1+X*PDPT
      PXPPH=PXPPH*DEL1+X*PDPP
      X=X*DEL1
      RETURN
      END