      SUBROUTINE TROUGH
      COMMON /CONST/ PI,PIT2,PID2,DUM(5)
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX
      COMMON R(6) /WW/ ID(10),WQ,W(400)
      EQUIVALENCE (A,W(151)),(B,W(152)),(ALAT,W(153)),(FACTOR,W(154))
      CHARACTER*6 MODX
      DATA MODX(2) /'TROUGH'/
      ENTRY ELECT1
      IF (X.EQ.0.0.AND.PXPR.EQ.0.0.AND.PXPTH.EQ.0.0.AND.PXPPH.EQ.0.0) RETURN
      IF (A.EQ.0.0) RETURN
      ANGLE=R(2)+ALAT-PID2
      WIDTH=B
      IF (ANGLE.GT.0.0) WIDTH=FACTOR*B
      ANGLE=ANGLE/WIDTH
      DELTA=A*EXP(-ANGLE**2)
      DEL1=DELTA+1.0
      PXPR=PXPR*DEL1
      PXPTH=PXPTH*DEL1-2.0*X*ANGLE*DELTA/WIDTH
      PXPPH=PXPPH*DEL1
      X=X*DEL1
      RETURN
      END