      SUBROUTINE WAVE
      COMMON /CONST/ PI,PIT2,PID2,DUM(5)
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT,HMAX
      COMMON R(6) /WW/ ID(10),WQ,W(400)
      EQUIVALENCE (EARTHR,W(2)),(ZO,W(151)),(SH,W(152)),(DELTA,W(153)),
     1 (VSUBX,W(154)),(LAMBDAX,W(155)),(LAMBDAZ,W(156)),(TP,W(157))
      REAL LAMBDAX,LAMBDAZ
      CHARACTER*6 MODX
      DATA MODX(2) /'WAVE'/
      ENTRY ELECT1
      IF (X.EQ.0.0.AND.PXPR.EQ.0.0.AND.PXPTH.EQ.0.0.AND.PXPPH.EQ.0.0) RETURN
      IF (DELTA.EQ.0.0.OR.SH.EQ.0.0) RETURN
      H=R(1)-EARTHR
      EXPO=EXP(-((H-ZO)/SH)**2)
      TMP=PIT2*(TP+(PID2-R(2))*EARTHR/LAMBDAX+H/LAMBDAZ)
      SINW=SIN(TMP)
      COSW=SIN(PID2-TMP)
      CONS=1.0+DELTA*EXPO*COSW
      IF (H.NE.0.0) PXPR=PXPR*CONS-X*DELTA*EXPO*(2.0/SH**2*(H-ZO)*COSW
     1 +PIT2/LAMBDAZ*SINW)
      PXPTH=PXPTH*CONS+X*DELTA*PIT2*EARTHR/LAMBDAX*SINW*EXPO
      PXPPH=PXPPH*CONS
      PXPT=0.0
      IF (VSUBX.NE.0.0) PXPT=-PIT2*VSUBX/LAMBDAX*X*DELTA*EXPO*SINW
      X=X*CONS
      RETURN
      END