      SUBROUTINE WAVE2
      COMMON /CONST/ PI,PIT2,PID2,DUM(5)
      COMMON /XX/ MODX(2),X,PXPR,PXPTH,PXPPH,PXPT
      COMMON R(6) /WW/ ID(10),WQ,W(400)
      EQUIVALENCE (EARTHR,W(2)),(ZO,W(151)),(SH,W(152)),(DELTA,W(153)),
     1 (VSUBX,W(154)),(LAMBDAX,W(155)),(LAMBDAZ,W(156)),(TP,W(157)),
     2 (THOO,W(158)),(THC,W(159)),(PHIC,W(160)),(VGX,W(161))
      REAL LAMBDAX,LAMBDAZ
      CHARACTER*6 MODX
      DATA MODX(2) /'WAVE2'/
      ENTRY ELECT1
      IF (X.EQ.0.0.AND.PXPR.EQ.0.0.AND.PXPTH.EQ.0.0.AND.PXPPH.EQ.0.0) RETURN
      IF (DELTA.EQ.0.0.OR.SH.EQ.0.0) RETURN
      H=R(1)-EARTHR
      THO=THOO+LAMBDAX*TP*VGX/VSUBX/EARTHR
      EXPR=EXP(-((H-ZO)/SH)**2)
      EXPTH=EXP(-((R(2)-THO)/THC)**2)
      EXPPHI=EXP(-(R(3)/PHIC)**2)
      WW=PIT2*(TP+(PID2-R(2))*EARTHR/LAMBDAX+H/LAMBDAZ)
      SINW=SIN(WW)
      COSW=COS(WW)
      E=DELTA*EXPR*EXPTH*EXPPHI
      CONS=1.0+E*COSW
      PXPR=PXPR*CONS-X*E*2.0*(COSW*(H-ZO)/SH**2+PI/LAMBDAZ*SINW)
      PXPTH=PXPTH*CONS+2.0*E*(X*PI*EARTHR*SINW/LAMBDAX-(R(2)-THO)/
     1 THC**2*COSW)
      PXPPH=PXPPH*CONS-X*2.0*E*R(3)/PHIC**2*COSW
      PXPT=-PIT2*VSUBX*E/LAMBDAX*SINW+2.0*E*VGX/EARTHR*COSW*(R(2)-THO
     1 -LAMBDAX*TP/EARTHR)/THC
      X=X*CONS
      RETURN
      END